language: java
script: mvn clean install --fail-at-end
notifications:
  email:
    on_failure: true
matrix:
  include:
  - jdk: openjdk7
    env: JACOCO=true
  - jdk: openjdk8
    env: JACOCO=true COVERALLS=true
  - jdk: oraclejdk8
    env: JACOCO=true
